spring:
  application:
    name: storage
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: public
    user: ${DB_USER}
    password: ${DB_PASSWORD}
server:
  port: ${PORT}
minio:
  bucket:
    name : user-files
